# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bekarysshaimardan/Desktop/chess-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bekarysshaimardan/Desktop/chess-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bekarysshaimardan/Desktop/chess-engine/CMakeFiles /Users/bekarysshaimardan/Desktop/chess-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bekarysshaimardan/Desktop/chess-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_engine

# Build rule for target.
chess_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_engine
.PHONY : chess_engine

# fast build rule for target.
chess_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/build
.PHONY : chess_engine/fast

#=============================================================================
# Target rules for targets named perft

# Build rule for target.
perft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perft
.PHONY : perft

# fast build rule for target.
perft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/build
.PHONY : perft/fast

src/bitboard.o: src/bitboard.cpp.o
.PHONY : src/bitboard.o

# target to build an object file
src/bitboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/bitboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/bitboard.cpp.o
.PHONY : src/bitboard.cpp.o

src/bitboard.i: src/bitboard.cpp.i
.PHONY : src/bitboard.i

# target to preprocess a source file
src/bitboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/bitboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/bitboard.cpp.i
.PHONY : src/bitboard.cpp.i

src/bitboard.s: src/bitboard.cpp.s
.PHONY : src/bitboard.s

# target to generate assembly for a file
src/bitboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/bitboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/bitboard.cpp.s
.PHONY : src/bitboard.cpp.s

src/board.o: src/board.cpp.o
.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/board.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/board.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/board.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/movegen.o: src/movegen.cpp.o
.PHONY : src/movegen.o

# target to build an object file
src/movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/movegen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/movegen.cpp.o
.PHONY : src/movegen.cpp.o

src/movegen.i: src/movegen.cpp.i
.PHONY : src/movegen.i

# target to preprocess a source file
src/movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/movegen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/movegen.cpp.i
.PHONY : src/movegen.cpp.i

src/movegen.s: src/movegen.cpp.s
.PHONY : src/movegen.s

# target to generate assembly for a file
src/movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/movegen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/src/movegen.cpp.s
.PHONY : src/movegen.cpp.s

tests/perft_test.o: tests/perft_test.cpp.o
.PHONY : tests/perft_test.o

# target to build an object file
tests/perft_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/tests/perft_test.cpp.o
.PHONY : tests/perft_test.cpp.o

tests/perft_test.i: tests/perft_test.cpp.i
.PHONY : tests/perft_test.i

# target to preprocess a source file
tests/perft_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/tests/perft_test.cpp.i
.PHONY : tests/perft_test.cpp.i

tests/perft_test.s: tests/perft_test.cpp.s
.PHONY : tests/perft_test.s

# target to generate assembly for a file
tests/perft_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perft.dir/build.make CMakeFiles/perft.dir/tests/perft_test.cpp.s
.PHONY : tests/perft_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... chess_engine"
	@echo "... perft"
	@echo "... src/bitboard.o"
	@echo "... src/bitboard.i"
	@echo "... src/bitboard.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/movegen.o"
	@echo "... src/movegen.i"
	@echo "... src/movegen.s"
	@echo "... tests/perft_test.o"
	@echo "... tests/perft_test.i"
	@echo "... tests/perft_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

